// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AccountMessage.proto

package com.passport.proto;

public final class AccountMessage {

  private static final com.google.protobuf.Descriptors.Descriptor
      internal_static_Account_descriptor;
  private static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Account_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;

  static {
    String[] descriptorData = {
        "\n\024AccountMessage.proto\"?\n\007Account\022\017\n\007add" +
            "ress\030\001 \001(\014\022\022\n\nprivateKey\030\002 \001(\014\022\017\n\007balanc" +
            "e\030\003 \001(\014B$\n\022com.passport.protoB\016AccountMe" +
            "ssageb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
        .internalBuildGeneratedFileFrom(descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[]{
            }, assigner);
    internal_static_Account_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_Account_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Account_descriptor,
        new String[]{"Address", "PrivateKey", "Balance",});
  }

  private AccountMessage() {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }

  public interface AccountOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Account)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes address = 1;</code>
     */
    com.google.protobuf.ByteString getAddress();

    /**
     * <code>bytes privateKey = 2;</code>
     */
    com.google.protobuf.ByteString getPrivateKey();

    /**
     * <code>bytes balance = 3;</code>
     */
    com.google.protobuf.ByteString getBalance();
  }

  /**
   * Protobuf type {@code Account}
   */
  public static final class Account extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Account)
      AccountOrBuilder {

    public static final int ADDRESS_FIELD_NUMBER = 1;
    public static final int PRIVATEKEY_FIELD_NUMBER = 2;
    public static final int BALANCE_FIELD_NUMBER = 3;
    private static final long serialVersionUID = 0L;
    // @@protoc_insertion_point(class_scope:Account)
    private static final AccountMessage.Account DEFAULT_INSTANCE;
    private static final com.google.protobuf.Parser<Account>
        PARSER = new com.google.protobuf.AbstractParser<Account>() {
      public Account parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Account(input, extensionRegistry);
      }
    };

    static {
      DEFAULT_INSTANCE = new AccountMessage.Account();
    }

    private com.google.protobuf.ByteString address_;
    private com.google.protobuf.ByteString privateKey_;
    private com.google.protobuf.ByteString balance_;
    private byte memoizedIsInitialized = -1;

    // Use Account.newBuilder() to construct.
    private Account(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }

    private Account() {
      address_ = com.google.protobuf.ByteString.EMPTY;
      privateKey_ = com.google.protobuf.ByteString.EMPTY;
      balance_ = com.google.protobuf.ByteString.EMPTY;
    }
    private Account(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              address_ = input.readBytes();
              break;
            }
            case 18: {

              privateKey_ = input.readBytes();
              break;
            }
            case 26: {

              balance_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return AccountMessage.internal_static_Account_descriptor;
    }

    public static AccountMessage.Account parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static AccountMessage.Account parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static AccountMessage.Account parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static AccountMessage.Account parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static AccountMessage.Account parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static AccountMessage.Account parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static AccountMessage.Account parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }

    public static AccountMessage.Account parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static AccountMessage.Account parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static AccountMessage.Account parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static AccountMessage.Account parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }

    public static AccountMessage.Account parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(AccountMessage.Account prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public static AccountMessage.Account getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static com.google.protobuf.Parser<Account> parser() {
      return PARSER;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }

    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
      return AccountMessage.internal_static_Account_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AccountMessage.Account.class, AccountMessage.Account.Builder.class);
    }

    /**
     * <code>bytes address = 1;</code>
     */
    public com.google.protobuf.ByteString getAddress() {
      return address_;
    }

    /**
     * <code>bytes privateKey = 2;</code>
     */
    public com.google.protobuf.ByteString getPrivateKey() {
      return privateKey_;
    }

    /**
     * <code>bytes balance = 3;</code>
     */
    public com.google.protobuf.ByteString getBalance() {
      return balance_;
    }

    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) {
        return true;
      }
      if (isInitialized == 0) {
        return false;
      }

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
        throws java.io.IOException {
      if (!address_.isEmpty()) {
        output.writeBytes(1, address_);
      }
      if (!privateKey_.isEmpty()) {
        output.writeBytes(2, privateKey_);
      }
      if (!balance_.isEmpty()) {
        output.writeBytes(3, balance_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) {
        return size;
      }

      size = 0;
      if (!address_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, address_);
      }
      if (!privateKey_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, privateKey_);
      }
      if (!balance_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(3, balance_);
      }
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof AccountMessage.Account)) {
        return super.equals(obj);
      }
      AccountMessage.Account other = (AccountMessage.Account) obj;

      boolean result = true;
      result = result && getAddress()
          .equals(other.getAddress());
      result = result && getPrivateKey()
          .equals(other.getPrivateKey());
      result = result && getBalance()
          .equals(other.getBalance());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
      hash = (37 * hash) + PRIVATEKEY_FIELD_NUMBER;
      hash = (53 * hash) + getPrivateKey().hashCode();
      hash = (37 * hash) + BALANCE_FIELD_NUMBER;
      hash = (53 * hash) + getBalance().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public Builder newBuilderForType() {
      return newBuilder();
    }

    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

    @Override
    public com.google.protobuf.Parser<Account> getParserForType() {
      return PARSER;
    }

    public AccountMessage.Account getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

    /**
     * Protobuf type {@code Account}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Account)
        AccountMessage.AccountOrBuilder {

      private com.google.protobuf.ByteString address_ = com.google.protobuf.ByteString.EMPTY;
      private com.google.protobuf.ByteString privateKey_ = com.google.protobuf.ByteString.EMPTY;
      private com.google.protobuf.ByteString balance_ = com.google.protobuf.ByteString.EMPTY;

      // Construct using com.passport.proto.AccountMessage.Account.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return AccountMessage.internal_static_Account_descriptor;
      }

      protected FieldAccessorTable
      internalGetFieldAccessorTable() {
        return AccountMessage.internal_static_Account_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                AccountMessage.Account.class, AccountMessage.Account.Builder.class);
      }

      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
            .alwaysUseFieldBuilders) {
        }
      }

      public Builder clear() {
        super.clear();
        address_ = com.google.protobuf.ByteString.EMPTY;

        privateKey_ = com.google.protobuf.ByteString.EMPTY;

        balance_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return AccountMessage.internal_static_Account_descriptor;
      }

      public AccountMessage.Account getDefaultInstanceForType() {
        return AccountMessage.Account.getDefaultInstance();
      }

      public AccountMessage.Account build() {
        AccountMessage.Account result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public AccountMessage.Account buildPartial() {
        AccountMessage.Account result = new AccountMessage.Account(this);
        result.address_ = address_;
        result.privateKey_ = privateKey_;
        result.balance_ = balance_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }

      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }

      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }

      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }

      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }

      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof AccountMessage.Account) {
          return mergeFrom((AccountMessage.Account) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(AccountMessage.Account other) {
        if (other == AccountMessage.Account.getDefaultInstance()) {
          return this;
        }
        if (other.getAddress() != com.google.protobuf.ByteString.EMPTY) {
          setAddress(other.getAddress());
        }
        if (other.getPrivateKey() != com.google.protobuf.ByteString.EMPTY) {
          setPrivateKey(other.getPrivateKey());
        }
        if (other.getBalance() != com.google.protobuf.ByteString.EMPTY) {
          setBalance(other.getBalance());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        AccountMessage.Account parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (AccountMessage.Account) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      /**
       * <code>bytes address = 1;</code>
       */
      public com.google.protobuf.ByteString getAddress() {
        return address_;
      }

      /**
       * <code>bytes address = 1;</code>
       */
      public Builder setAddress(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }

        address_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>bytes address = 1;</code>
       */
      public Builder clearAddress() {

        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }

      /**
       * <code>bytes privateKey = 2;</code>
       */
      public com.google.protobuf.ByteString getPrivateKey() {
        return privateKey_;
      }

      /**
       * <code>bytes privateKey = 2;</code>
       */
      public Builder setPrivateKey(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }

        privateKey_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>bytes privateKey = 2;</code>
       */
      public Builder clearPrivateKey() {

        privateKey_ = getDefaultInstance().getPrivateKey();
        onChanged();
        return this;
      }

      /**
       * <code>bytes balance = 3;</code>
       */
      public com.google.protobuf.ByteString getBalance() {
        return balance_;
      }

      /**
       * <code>bytes balance = 3;</code>
       */
      public Builder setBalance(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }

        balance_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>bytes balance = 3;</code>
       */
      public Builder clearBalance() {

        balance_ = getDefaultInstance().getBalance();
        onChanged();
        return this;
      }

      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Account)
    }

  }

  // @@protoc_insertion_point(outer_class_scope)
}
