// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BlockMessage.proto

package com.passport.proto;

public final class BlockMessage {
  private BlockMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BlockOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Block)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 blockSize = 1;</code>
     */
    long getBlockSize();

    /**
     * <code>int64 blockHeight = 2;</code>
     */
    long getBlockHeight();

    /**
     * <code>.BlockHeader blockHeader = 3;</code>
     */
    boolean hasBlockHeader();
    /**
     * <code>.BlockHeader blockHeader = 3;</code>
     */
    BlockHeaderMessage.BlockHeader getBlockHeader();
    /**
     * <code>.BlockHeader blockHeader = 3;</code>
     */
    BlockHeaderMessage.BlockHeaderOrBuilder getBlockHeaderOrBuilder();

    /**
     * <code>int32 transactionCount = 4;</code>
     */
    int getTransactionCount();

    /**
     * <code>.Transaction transactions = 5;</code>
     */
    boolean hasTransactions();
    /**
     * <code>.Transaction transactions = 5;</code>
     */
    TransactionMessage.Transaction getTransactions();
    /**
     * <code>.Transaction transactions = 5;</code>
     */
    TransactionMessage.TransactionOrBuilder getTransactionsOrBuilder();
  }
  /**
   * Protobuf type {@code Block}
   */
  public  static final class Block extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Block)
      BlockOrBuilder {
    // Use Block.newBuilder() to construct.
    private Block(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Block() {
      blockSize_ = 0L;
      blockHeight_ = 0L;
      transactionCount_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Block(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              blockSize_ = input.readInt64();
              break;
            }
            case 16: {

              blockHeight_ = input.readInt64();
              break;
            }
            case 26: {
              BlockHeaderMessage.BlockHeader.Builder subBuilder = null;
              if (blockHeader_ != null) {
                subBuilder = blockHeader_.toBuilder();
              }
              blockHeader_ = input.readMessage(BlockHeaderMessage.BlockHeader.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(blockHeader_);
                blockHeader_ = subBuilder.buildPartial();
              }

              break;
            }
            case 32: {

              transactionCount_ = input.readInt32();
              break;
            }
            case 42: {
              TransactionMessage.Transaction.Builder subBuilder = null;
              if (transactions_ != null) {
                subBuilder = transactions_.toBuilder();
              }
              transactions_ = input.readMessage(TransactionMessage.Transaction.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(transactions_);
                transactions_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BlockMessage.internal_static_Block_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BlockMessage.internal_static_Block_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              BlockMessage.Block.class, BlockMessage.Block.Builder.class);
    }

    public static final int BLOCKSIZE_FIELD_NUMBER = 1;
    private long blockSize_;
    /**
     * <code>int64 blockSize = 1;</code>
     */
    public long getBlockSize() {
      return blockSize_;
    }

    public static final int BLOCKHEIGHT_FIELD_NUMBER = 2;
    private long blockHeight_;
    /**
     * <code>int64 blockHeight = 2;</code>
     */
    public long getBlockHeight() {
      return blockHeight_;
    }

    public static final int BLOCKHEADER_FIELD_NUMBER = 3;
    private BlockHeaderMessage.BlockHeader blockHeader_;
    /**
     * <code>.BlockHeader blockHeader = 3;</code>
     */
    public boolean hasBlockHeader() {
      return blockHeader_ != null;
    }
    /**
     * <code>.BlockHeader blockHeader = 3;</code>
     */
    public BlockHeaderMessage.BlockHeader getBlockHeader() {
      return blockHeader_ == null ? BlockHeaderMessage.BlockHeader.getDefaultInstance() : blockHeader_;
    }
    /**
     * <code>.BlockHeader blockHeader = 3;</code>
     */
    public BlockHeaderMessage.BlockHeaderOrBuilder getBlockHeaderOrBuilder() {
      return getBlockHeader();
    }

    public static final int TRANSACTIONCOUNT_FIELD_NUMBER = 4;
    private int transactionCount_;
    /**
     * <code>int32 transactionCount = 4;</code>
     */
    public int getTransactionCount() {
      return transactionCount_;
    }

    public static final int TRANSACTIONS_FIELD_NUMBER = 5;
    private TransactionMessage.Transaction transactions_;
    /**
     * <code>.Transaction transactions = 5;</code>
     */
    public boolean hasTransactions() {
      return transactions_ != null;
    }
    /**
     * <code>.Transaction transactions = 5;</code>
     */
    public TransactionMessage.Transaction getTransactions() {
      return transactions_ == null ? TransactionMessage.Transaction.getDefaultInstance() : transactions_;
    }
    /**
     * <code>.Transaction transactions = 5;</code>
     */
    public TransactionMessage.TransactionOrBuilder getTransactionsOrBuilder() {
      return getTransactions();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (blockSize_ != 0L) {
        output.writeInt64(1, blockSize_);
      }
      if (blockHeight_ != 0L) {
        output.writeInt64(2, blockHeight_);
      }
      if (blockHeader_ != null) {
        output.writeMessage(3, getBlockHeader());
      }
      if (transactionCount_ != 0) {
        output.writeInt32(4, transactionCount_);
      }
      if (transactions_ != null) {
        output.writeMessage(5, getTransactions());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (blockSize_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, blockSize_);
      }
      if (blockHeight_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, blockHeight_);
      }
      if (blockHeader_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getBlockHeader());
      }
      if (transactionCount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, transactionCount_);
      }
      if (transactions_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getTransactions());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof BlockMessage.Block)) {
        return super.equals(obj);
      }
      BlockMessage.Block other = (BlockMessage.Block) obj;

      boolean result = true;
      result = result && (getBlockSize()
          == other.getBlockSize());
      result = result && (getBlockHeight()
          == other.getBlockHeight());
      result = result && (hasBlockHeader() == other.hasBlockHeader());
      if (hasBlockHeader()) {
        result = result && getBlockHeader()
            .equals(other.getBlockHeader());
      }
      result = result && (getTransactionCount()
          == other.getTransactionCount());
      result = result && (hasTransactions() == other.hasTransactions());
      if (hasTransactions()) {
        result = result && getTransactions()
            .equals(other.getTransactions());
      }
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BLOCKSIZE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getBlockSize());
      hash = (37 * hash) + BLOCKHEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getBlockHeight());
      if (hasBlockHeader()) {
        hash = (37 * hash) + BLOCKHEADER_FIELD_NUMBER;
        hash = (53 * hash) + getBlockHeader().hashCode();
      }
      hash = (37 * hash) + TRANSACTIONCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getTransactionCount();
      if (hasTransactions()) {
        hash = (37 * hash) + TRANSACTIONS_FIELD_NUMBER;
        hash = (53 * hash) + getTransactions().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static BlockMessage.Block parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BlockMessage.Block parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BlockMessage.Block parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BlockMessage.Block parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BlockMessage.Block parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BlockMessage.Block parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BlockMessage.Block parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static BlockMessage.Block parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static BlockMessage.Block parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static BlockMessage.Block parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static BlockMessage.Block parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static BlockMessage.Block parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(BlockMessage.Block prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Block}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Block)
        BlockMessage.BlockOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BlockMessage.internal_static_Block_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BlockMessage.internal_static_Block_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                BlockMessage.Block.class, BlockMessage.Block.Builder.class);
      }

      // Construct using com.passport.proto.BlockMessage.Block.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        blockSize_ = 0L;

        blockHeight_ = 0L;

        if (blockHeaderBuilder_ == null) {
          blockHeader_ = null;
        } else {
          blockHeader_ = null;
          blockHeaderBuilder_ = null;
        }
        transactionCount_ = 0;

        if (transactionsBuilder_ == null) {
          transactions_ = null;
        } else {
          transactions_ = null;
          transactionsBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BlockMessage.internal_static_Block_descriptor;
      }

      public BlockMessage.Block getDefaultInstanceForType() {
        return BlockMessage.Block.getDefaultInstance();
      }

      public BlockMessage.Block build() {
        BlockMessage.Block result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public BlockMessage.Block buildPartial() {
        BlockMessage.Block result = new BlockMessage.Block(this);
        result.blockSize_ = blockSize_;
        result.blockHeight_ = blockHeight_;
        if (blockHeaderBuilder_ == null) {
          result.blockHeader_ = blockHeader_;
        } else {
          result.blockHeader_ = blockHeaderBuilder_.build();
        }
        result.transactionCount_ = transactionCount_;
        if (transactionsBuilder_ == null) {
          result.transactions_ = transactions_;
        } else {
          result.transactions_ = transactionsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof BlockMessage.Block) {
          return mergeFrom((BlockMessage.Block)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(BlockMessage.Block other) {
        if (other == BlockMessage.Block.getDefaultInstance()) return this;
        if (other.getBlockSize() != 0L) {
          setBlockSize(other.getBlockSize());
        }
        if (other.getBlockHeight() != 0L) {
          setBlockHeight(other.getBlockHeight());
        }
        if (other.hasBlockHeader()) {
          mergeBlockHeader(other.getBlockHeader());
        }
        if (other.getTransactionCount() != 0) {
          setTransactionCount(other.getTransactionCount());
        }
        if (other.hasTransactions()) {
          mergeTransactions(other.getTransactions());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        BlockMessage.Block parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (BlockMessage.Block) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long blockSize_ ;
      /**
       * <code>int64 blockSize = 1;</code>
       */
      public long getBlockSize() {
        return blockSize_;
      }
      /**
       * <code>int64 blockSize = 1;</code>
       */
      public Builder setBlockSize(long value) {

        blockSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 blockSize = 1;</code>
       */
      public Builder clearBlockSize() {

        blockSize_ = 0L;
        onChanged();
        return this;
      }

      private long blockHeight_ ;
      /**
       * <code>int64 blockHeight = 2;</code>
       */
      public long getBlockHeight() {
        return blockHeight_;
      }
      /**
       * <code>int64 blockHeight = 2;</code>
       */
      public Builder setBlockHeight(long value) {

        blockHeight_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 blockHeight = 2;</code>
       */
      public Builder clearBlockHeight() {

        blockHeight_ = 0L;
        onChanged();
        return this;
      }

      private BlockHeaderMessage.BlockHeader blockHeader_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          BlockHeaderMessage.BlockHeader, BlockHeaderMessage.BlockHeader.Builder, BlockHeaderMessage.BlockHeaderOrBuilder> blockHeaderBuilder_;
      /**
       * <code>.BlockHeader blockHeader = 3;</code>
       */
      public boolean hasBlockHeader() {
        return blockHeaderBuilder_ != null || blockHeader_ != null;
      }
      /**
       * <code>.BlockHeader blockHeader = 3;</code>
       */
      public BlockHeaderMessage.BlockHeader getBlockHeader() {
        if (blockHeaderBuilder_ == null) {
          return blockHeader_ == null ? BlockHeaderMessage.BlockHeader.getDefaultInstance() : blockHeader_;
        } else {
          return blockHeaderBuilder_.getMessage();
        }
      }
      /**
       * <code>.BlockHeader blockHeader = 3;</code>
       */
      public Builder setBlockHeader(BlockHeaderMessage.BlockHeader value) {
        if (blockHeaderBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          blockHeader_ = value;
          onChanged();
        } else {
          blockHeaderBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.BlockHeader blockHeader = 3;</code>
       */
      public Builder setBlockHeader(
          BlockHeaderMessage.BlockHeader.Builder builderForValue) {
        if (blockHeaderBuilder_ == null) {
          blockHeader_ = builderForValue.build();
          onChanged();
        } else {
          blockHeaderBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.BlockHeader blockHeader = 3;</code>
       */
      public Builder mergeBlockHeader(BlockHeaderMessage.BlockHeader value) {
        if (blockHeaderBuilder_ == null) {
          if (blockHeader_ != null) {
            blockHeader_ =
              BlockHeaderMessage.BlockHeader.newBuilder(blockHeader_).mergeFrom(value).buildPartial();
          } else {
            blockHeader_ = value;
          }
          onChanged();
        } else {
          blockHeaderBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.BlockHeader blockHeader = 3;</code>
       */
      public Builder clearBlockHeader() {
        if (blockHeaderBuilder_ == null) {
          blockHeader_ = null;
          onChanged();
        } else {
          blockHeader_ = null;
          blockHeaderBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.BlockHeader blockHeader = 3;</code>
       */
      public BlockHeaderMessage.BlockHeader.Builder getBlockHeaderBuilder() {

        onChanged();
        return getBlockHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>.BlockHeader blockHeader = 3;</code>
       */
      public BlockHeaderMessage.BlockHeaderOrBuilder getBlockHeaderOrBuilder() {
        if (blockHeaderBuilder_ != null) {
          return blockHeaderBuilder_.getMessageOrBuilder();
        } else {
          return blockHeader_ == null ?
              BlockHeaderMessage.BlockHeader.getDefaultInstance() : blockHeader_;
        }
      }
      /**
       * <code>.BlockHeader blockHeader = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          BlockHeaderMessage.BlockHeader, BlockHeaderMessage.BlockHeader.Builder, BlockHeaderMessage.BlockHeaderOrBuilder>
          getBlockHeaderFieldBuilder() {
        if (blockHeaderBuilder_ == null) {
          blockHeaderBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              BlockHeaderMessage.BlockHeader, BlockHeaderMessage.BlockHeader.Builder, BlockHeaderMessage.BlockHeaderOrBuilder>(
                  getBlockHeader(),
                  getParentForChildren(),
                  isClean());
          blockHeader_ = null;
        }
        return blockHeaderBuilder_;
      }

      private int transactionCount_ ;
      /**
       * <code>int32 transactionCount = 4;</code>
       */
      public int getTransactionCount() {
        return transactionCount_;
      }
      /**
       * <code>int32 transactionCount = 4;</code>
       */
      public Builder setTransactionCount(int value) {

        transactionCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 transactionCount = 4;</code>
       */
      public Builder clearTransactionCount() {

        transactionCount_ = 0;
        onChanged();
        return this;
      }

      private TransactionMessage.Transaction transactions_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          TransactionMessage.Transaction, TransactionMessage.Transaction.Builder, TransactionMessage.TransactionOrBuilder> transactionsBuilder_;
      /**
       * <code>.Transaction transactions = 5;</code>
       */
      public boolean hasTransactions() {
        return transactionsBuilder_ != null || transactions_ != null;
      }
      /**
       * <code>.Transaction transactions = 5;</code>
       */
      public TransactionMessage.Transaction getTransactions() {
        if (transactionsBuilder_ == null) {
          return transactions_ == null ? TransactionMessage.Transaction.getDefaultInstance() : transactions_;
        } else {
          return transactionsBuilder_.getMessage();
        }
      }
      /**
       * <code>.Transaction transactions = 5;</code>
       */
      public Builder setTransactions(TransactionMessage.Transaction value) {
        if (transactionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          transactions_ = value;
          onChanged();
        } else {
          transactionsBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Transaction transactions = 5;</code>
       */
      public Builder setTransactions(
          TransactionMessage.Transaction.Builder builderForValue) {
        if (transactionsBuilder_ == null) {
          transactions_ = builderForValue.build();
          onChanged();
        } else {
          transactionsBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Transaction transactions = 5;</code>
       */
      public Builder mergeTransactions(TransactionMessage.Transaction value) {
        if (transactionsBuilder_ == null) {
          if (transactions_ != null) {
            transactions_ =
              TransactionMessage.Transaction.newBuilder(transactions_).mergeFrom(value).buildPartial();
          } else {
            transactions_ = value;
          }
          onChanged();
        } else {
          transactionsBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Transaction transactions = 5;</code>
       */
      public Builder clearTransactions() {
        if (transactionsBuilder_ == null) {
          transactions_ = null;
          onChanged();
        } else {
          transactions_ = null;
          transactionsBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Transaction transactions = 5;</code>
       */
      public TransactionMessage.Transaction.Builder getTransactionsBuilder() {

        onChanged();
        return getTransactionsFieldBuilder().getBuilder();
      }
      /**
       * <code>.Transaction transactions = 5;</code>
       */
      public TransactionMessage.TransactionOrBuilder getTransactionsOrBuilder() {
        if (transactionsBuilder_ != null) {
          return transactionsBuilder_.getMessageOrBuilder();
        } else {
          return transactions_ == null ?
              TransactionMessage.Transaction.getDefaultInstance() : transactions_;
        }
      }
      /**
       * <code>.Transaction transactions = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          TransactionMessage.Transaction, TransactionMessage.Transaction.Builder, TransactionMessage.TransactionOrBuilder>
          getTransactionsFieldBuilder() {
        if (transactionsBuilder_ == null) {
          transactionsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              TransactionMessage.Transaction, TransactionMessage.Transaction.Builder, TransactionMessage.TransactionOrBuilder>(
                  getTransactions(),
                  getParentForChildren(),
                  isClean());
          transactions_ = null;
        }
        return transactionsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Block)
    }

    // @@protoc_insertion_point(class_scope:Block)
    private static final BlockMessage.Block DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new BlockMessage.Block();
    }

    public static BlockMessage.Block getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Block>
        PARSER = new com.google.protobuf.AbstractParser<Block>() {
      public Block parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Block(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Block> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Block> getParserForType() {
      return PARSER;
    }

    public BlockMessage.Block getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Block_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Block_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022BlockMessage.proto\032\030BlockHeaderMessage" +
      ".proto\032\030TransactionMessage.proto\"\220\001\n\005Blo" +
      "ck\022\021\n\tblockSize\030\001 \001(\003\022\023\n\013blockHeight\030\002 \001" +
      "(\003\022!\n\013blockHeader\030\003 \001(\0132\014.BlockHeader\022\030\n" +
      "\020transactionCount\030\004 \001(\005\022\"\n\014transactions\030" +
      "\005 \001(\0132\014.TransactionB\"\n\022com.passport.prot" +
      "oB\014BlockMessageb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          BlockHeaderMessage.getDescriptor(),
          TransactionMessage.getDescriptor(),
        }, assigner);
    internal_static_Block_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Block_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Block_descriptor,
        new String[] { "BlockSize", "BlockHeight", "BlockHeader", "TransactionCount", "Transactions", });
    BlockHeaderMessage.getDescriptor();
    TransactionMessage.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
