// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataType.proto

package com.passport.proto;

public final class DataTypeEnum {

  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;

  static {
    String[] descriptorData = {
        "\n\016DataType.proto*}\n\010DataType\022\016\n\nHEART_BE" +
            "AT\020\000\022\023\n\017NEXT_BLOCK_SYNC\020\001\022\024\n\020ACCOUNTLIST" +
            "_SYNC\020\002\022\020\n\014ACCOUNT_SYNC\020\003\022\024\n\020SEND_TRANSA" +
            "CTION\020\004\022\016\n\nBLOCK_SYNC\020\005B\"\n\022com.passport." +
            "protoB\014DataTypeEnumb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
        .internalBuildGeneratedFileFrom(descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[]{
            }, assigner);
  }

  private DataTypeEnum() {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }

  /**
   * Protobuf enum {@code DataType}
   */
  public enum DataType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>HEART_BEAT = 0;</code>
     */
    HEART_BEAT(0),
    /**
     * <code>NEXT_BLOCK_SYNC = 1;</code>
     */
    NEXT_BLOCK_SYNC(1),
    /**
     * <code>ACCOUNTLIST_SYNC = 2;</code>
     */
    ACCOUNTLIST_SYNC(2),
    /**
     * <code>ACCOUNT_SYNC = 3;</code>
     */
    ACCOUNT_SYNC(3),
    /**
     * <code>SEND_TRANSACTION = 4;</code>
     */
    SEND_TRANSACTION(4),
    /**
     * <code>BLOCK_SYNC = 5;</code>
     */
    BLOCK_SYNC(5),
    UNRECOGNIZED(-1),;

    /**
     * <code>HEART_BEAT = 0;</code>
     */
    public static final int HEART_BEAT_VALUE = 0;
    /**
     * <code>NEXT_BLOCK_SYNC = 1;</code>
     */
    public static final int NEXT_BLOCK_SYNC_VALUE = 1;
    /**
     * <code>ACCOUNTLIST_SYNC = 2;</code>
     */
    public static final int ACCOUNTLIST_SYNC_VALUE = 2;
    /**
     * <code>ACCOUNT_SYNC = 3;</code>
     */
    public static final int ACCOUNT_SYNC_VALUE = 3;
    /**
     * <code>SEND_TRANSACTION = 4;</code>
     */
    public static final int SEND_TRANSACTION_VALUE = 4;
    /**
     * <code>BLOCK_SYNC = 5;</code>
     */
    public static final int BLOCK_SYNC_VALUE = 5;
    private static final com.google.protobuf.Internal.EnumLiteMap<
        DataType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<DataType>() {
          public DataType findValueByNumber(int number) {
            return DataType.forNumber(number);
          }
        };
    private static final DataType[] VALUES = values();
    private final int value;

    private DataType(int value) {
      this.value = value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static DataType valueOf(int value) {
      return forNumber(value);
    }

    public static DataType forNumber(int value) {
      switch (value) {
        case 0:
          return HEART_BEAT;
        case 1:
          return NEXT_BLOCK_SYNC;
        case 2:
          return ACCOUNTLIST_SYNC;
        case 3:
          return ACCOUNT_SYNC;
        case 4:
          return SEND_TRANSACTION;
        case 5:
          return BLOCK_SYNC;
        default:
          return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<DataType>
    internalGetValueMap() {
      return internalValueMap;
    }

    public static final com.google.protobuf.Descriptors.EnumDescriptor
    getDescriptor() {
      return DataTypeEnum.getDescriptor().getEnumTypes().get(0);
    }

    public static DataType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
    getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }

    public final com.google.protobuf.Descriptors.EnumDescriptor
    getDescriptorForType() {
      return getDescriptor();
    }

    // @@protoc_insertion_point(enum_scope:DataType)
  }

  // @@protoc_insertion_point(outer_class_scope)
}
