// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NettyMessage.proto

package com.passport.proto;

public final class NettyMessage {
<<<<<<< HEAD
  private NettyMessage() {}
=======

  private static final com.google.protobuf.Descriptors.Descriptor
      internal_static_Message_descriptor;
  private static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;

  static {
    String[] descriptorData = {
        "\n\022NettyMessage.proto\032\021MessageType.proto\032" +
            "\017NettyData.proto\"A\n\007Message\022!\n\013messageTy" +
            "pe\030\001 \001(\0162\014.MessageType\022\023\n\004data\030\002 \001(\0132\005.D" +
            "ataB\"\n\022com.passport.protoB\014NettyMessageb" +
            "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
        .internalBuildGeneratedFileFrom(descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[]{
                MessageTypeEnum.getDescriptor(),
                NettyData.getDescriptor(),
            }, assigner);
    internal_static_Message_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_Message_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_descriptor,
        new String[]{"MessageType", "Data",});
    MessageTypeEnum.getDescriptor();
    NettyData.getDescriptor();
  }

  private NettyMessage() {
  }

>>>>>>> a1abf2231ceadb16c3538774fc50b7415b1816d4
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
<<<<<<< HEAD
=======

  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }

>>>>>>> a1abf2231ceadb16c3538774fc50b7415b1816d4
  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.MessageType messageType = 1;</code>
     */
    int getMessageTypeValue();
<<<<<<< HEAD
=======

>>>>>>> a1abf2231ceadb16c3538774fc50b7415b1816d4
    /**
     * <code>.MessageType messageType = 1;</code>
     */
    MessageTypeEnum.MessageType getMessageType();

    /**
     * <code>.Data data = 2;</code>
     */
    boolean hasData();
<<<<<<< HEAD
=======

>>>>>>> a1abf2231ceadb16c3538774fc50b7415b1816d4
    /**
     * <code>.Data data = 2;</code>
     */
    NettyData.Data getData();
<<<<<<< HEAD
=======

>>>>>>> a1abf2231ceadb16c3538774fc50b7415b1816d4
    /**
     * <code>.Data data = 2;</code>
     */
    NettyData.DataOrBuilder getDataOrBuilder();
  }
<<<<<<< HEAD
  /**
   * Protobuf type {@code Message}
   */
  public  static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Message)
      MessageOrBuilder {
=======

  /**
   * Protobuf type {@code Message}
   */
  public static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Message)
      MessageOrBuilder {

    public static final int MESSAGETYPE_FIELD_NUMBER = 1;
    public static final int DATA_FIELD_NUMBER = 2;
    private static final long serialVersionUID = 0L;
    // @@protoc_insertion_point(class_scope:Message)
    private static final NettyMessage.Message DEFAULT_INSTANCE;
    private static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Message(input, extensionRegistry);
      }
    };

    static {
      DEFAULT_INSTANCE = new NettyMessage.Message();
    }

    private int messageType_;
    private NettyData.Data data_;
    private byte memoizedIsInitialized = -1;

>>>>>>> a1abf2231ceadb16c3538774fc50b7415b1816d4
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
<<<<<<< HEAD
    private Message() {
      messageType_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
=======

    private Message() {
      messageType_ = 0;
    }
>>>>>>> a1abf2231ceadb16c3538774fc50b7415b1816d4
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              messageType_ = rawValue;
              break;
            }
            case 18: {
              NettyData.Data.Builder subBuilder = null;
              if (data_ != null) {
                subBuilder = data_.toBuilder();
              }
              data_ = input.readMessage(NettyData.Data.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(data_);
                data_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
<<<<<<< HEAD
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return NettyMessage.internal_static_Message_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
=======

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return NettyMessage.internal_static_Message_descriptor;
    }

    public static NettyMessage.Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static NettyMessage.Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static NettyMessage.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static NettyMessage.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static NettyMessage.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static NettyMessage.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static NettyMessage.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }

    public static NettyMessage.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static NettyMessage.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static NettyMessage.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static NettyMessage.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }

    public static NettyMessage.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(NettyMessage.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public static NettyMessage.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }

    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
>>>>>>> a1abf2231ceadb16c3538774fc50b7415b1816d4
      return NettyMessage.internal_static_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              NettyMessage.Message.class, NettyMessage.Message.Builder.class);
    }

<<<<<<< HEAD
    public static final int MESSAGETYPE_FIELD_NUMBER = 1;
    private int messageType_;
=======
>>>>>>> a1abf2231ceadb16c3538774fc50b7415b1816d4
    /**
     * <code>.MessageType messageType = 1;</code>
     */
    public int getMessageTypeValue() {
      return messageType_;
    }
<<<<<<< HEAD
=======

>>>>>>> a1abf2231ceadb16c3538774fc50b7415b1816d4
    /**
     * <code>.MessageType messageType = 1;</code>
     */
    public MessageTypeEnum.MessageType getMessageType() {
      MessageTypeEnum.MessageType result = MessageTypeEnum.MessageType.valueOf(messageType_);
      return result == null ? MessageTypeEnum.MessageType.UNRECOGNIZED : result;
    }

<<<<<<< HEAD
    public static final int DATA_FIELD_NUMBER = 2;
    private NettyData.Data data_;
=======
>>>>>>> a1abf2231ceadb16c3538774fc50b7415b1816d4
    /**
     * <code>.Data data = 2;</code>
     */
    public boolean hasData() {
      return data_ != null;
    }
<<<<<<< HEAD
=======

>>>>>>> a1abf2231ceadb16c3538774fc50b7415b1816d4
    /**
     * <code>.Data data = 2;</code>
     */
    public NettyData.Data getData() {
      return data_ == null ? NettyData.Data.getDefaultInstance() : data_;
    }
<<<<<<< HEAD
=======

>>>>>>> a1abf2231ceadb16c3538774fc50b7415b1816d4
    /**
     * <code>.Data data = 2;</code>
     */
    public NettyData.DataOrBuilder getDataOrBuilder() {
      return getData();
    }

<<<<<<< HEAD
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;
=======
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) {
        return true;
      }
      if (isInitialized == 0) {
        return false;
      }
>>>>>>> a1abf2231ceadb16c3538774fc50b7415b1816d4

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
<<<<<<< HEAD
                        throws java.io.IOException {
=======
        throws java.io.IOException {
>>>>>>> a1abf2231ceadb16c3538774fc50b7415b1816d4
      if (messageType_ != MessageTypeEnum.MessageType.DATA_REQ.getNumber()) {
        output.writeEnum(1, messageType_);
      }
      if (data_ != null) {
        output.writeMessage(2, getData());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
<<<<<<< HEAD
      if (size != -1) return size;
=======
      if (size != -1) {
        return size;
      }
>>>>>>> a1abf2231ceadb16c3538774fc50b7415b1816d4

      size = 0;
      if (messageType_ != MessageTypeEnum.MessageType.DATA_REQ.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
<<<<<<< HEAD
          .computeEnumSize(1, messageType_);
      }
      if (data_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getData());
=======
            .computeEnumSize(1, messageType_);
      }
      if (data_ != null) {
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, getData());
>>>>>>> a1abf2231ceadb16c3538774fc50b7415b1816d4
      }
      memoizedSize = size;
      return size;
    }

<<<<<<< HEAD
    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
=======
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
        return true;
>>>>>>> a1abf2231ceadb16c3538774fc50b7415b1816d4
      }
      if (!(obj instanceof NettyMessage.Message)) {
        return super.equals(obj);
      }
      NettyMessage.Message other = (NettyMessage.Message) obj;

      boolean result = true;
      result = result && messageType_ == other.messageType_;
      result = result && (hasData() == other.hasData());
      if (hasData()) {
        result = result && getData()
            .equals(other.getData());
      }
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MESSAGETYPE_FIELD_NUMBER;
      hash = (53 * hash) + messageType_;
      if (hasData()) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getData().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

<<<<<<< HEAD
    public static NettyMessage.Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NettyMessage.Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NettyMessage.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NettyMessage.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NettyMessage.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NettyMessage.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NettyMessage.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static NettyMessage.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static NettyMessage.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static NettyMessage.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static NettyMessage.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static NettyMessage.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(NettyMessage.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
=======
    public Builder newBuilderForType() {
      return newBuilder();
    }

>>>>>>> a1abf2231ceadb16c3538774fc50b7415b1816d4
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
<<<<<<< HEAD
=======

    @Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    public NettyMessage.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

>>>>>>> a1abf2231ceadb16c3538774fc50b7415b1816d4
    /**
     * Protobuf type {@code Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Message)
        NettyMessage.MessageOrBuilder {
<<<<<<< HEAD
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return NettyMessage.internal_static_Message_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return NettyMessage.internal_static_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                NettyMessage.Message.class, NettyMessage.Message.Builder.class);
      }
=======

      private int messageType_ = 0;
      private NettyData.Data data_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          NettyData.Data, NettyData.Data.Builder, NettyData.DataOrBuilder> dataBuilder_;
>>>>>>> a1abf2231ceadb16c3538774fc50b7415b1816d4

      // Construct using com.passport.proto.NettyMessage.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
<<<<<<< HEAD
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
=======

      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return NettyMessage.internal_static_Message_descriptor;
      }

      protected FieldAccessorTable
      internalGetFieldAccessorTable() {
        return NettyMessage.internal_static_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                NettyMessage.Message.class, NettyMessage.Message.Builder.class);
      }

      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
            .alwaysUseFieldBuilders) {
        }
      }

>>>>>>> a1abf2231ceadb16c3538774fc50b7415b1816d4
      public Builder clear() {
        super.clear();
        messageType_ = 0;

        if (dataBuilder_ == null) {
          data_ = null;
        } else {
          data_ = null;
          dataBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
<<<<<<< HEAD
          getDescriptorForType() {
=======
      getDescriptorForType() {
>>>>>>> a1abf2231ceadb16c3538774fc50b7415b1816d4
        return NettyMessage.internal_static_Message_descriptor;
      }

      public NettyMessage.Message getDefaultInstanceForType() {
        return NettyMessage.Message.getDefaultInstance();
      }

      public NettyMessage.Message build() {
        NettyMessage.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public NettyMessage.Message buildPartial() {
        NettyMessage.Message result = new NettyMessage.Message(this);
        result.messageType_ = messageType_;
        if (dataBuilder_ == null) {
          result.data_ = data_;
        } else {
          result.data_ = dataBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
<<<<<<< HEAD
=======

>>>>>>> a1abf2231ceadb16c3538774fc50b7415b1816d4
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
<<<<<<< HEAD
=======

>>>>>>> a1abf2231ceadb16c3538774fc50b7415b1816d4
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
<<<<<<< HEAD
=======

>>>>>>> a1abf2231ceadb16c3538774fc50b7415b1816d4
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
<<<<<<< HEAD
=======

>>>>>>> a1abf2231ceadb16c3538774fc50b7415b1816d4
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
<<<<<<< HEAD
=======

>>>>>>> a1abf2231ceadb16c3538774fc50b7415b1816d4
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
<<<<<<< HEAD
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof NettyMessage.Message) {
          return mergeFrom((NettyMessage.Message)other);
=======

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof NettyMessage.Message) {
          return mergeFrom((NettyMessage.Message) other);
>>>>>>> a1abf2231ceadb16c3538774fc50b7415b1816d4
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(NettyMessage.Message other) {
<<<<<<< HEAD
        if (other == NettyMessage.Message.getDefaultInstance()) return this;
=======
        if (other == NettyMessage.Message.getDefaultInstance()) {
          return this;
        }
>>>>>>> a1abf2231ceadb16c3538774fc50b7415b1816d4
        if (other.messageType_ != 0) {
          setMessageTypeValue(other.getMessageTypeValue());
        }
        if (other.hasData()) {
          mergeData(other.getData());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        NettyMessage.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (NettyMessage.Message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

<<<<<<< HEAD
      private int messageType_ = 0;
=======
>>>>>>> a1abf2231ceadb16c3538774fc50b7415b1816d4
      /**
       * <code>.MessageType messageType = 1;</code>
       */
      public int getMessageTypeValue() {
        return messageType_;
      }
<<<<<<< HEAD
=======

>>>>>>> a1abf2231ceadb16c3538774fc50b7415b1816d4
      /**
       * <code>.MessageType messageType = 1;</code>
       */
      public Builder setMessageTypeValue(int value) {
        messageType_ = value;
        onChanged();
        return this;
      }
<<<<<<< HEAD
=======

>>>>>>> a1abf2231ceadb16c3538774fc50b7415b1816d4
      /**
       * <code>.MessageType messageType = 1;</code>
       */
      public MessageTypeEnum.MessageType getMessageType() {
        MessageTypeEnum.MessageType result = MessageTypeEnum.MessageType.valueOf(messageType_);
        return result == null ? MessageTypeEnum.MessageType.UNRECOGNIZED : result;
      }
<<<<<<< HEAD
=======

>>>>>>> a1abf2231ceadb16c3538774fc50b7415b1816d4
      /**
       * <code>.MessageType messageType = 1;</code>
       */
      public Builder setMessageType(MessageTypeEnum.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }

        messageType_ = value.getNumber();
        onChanged();
        return this;
      }
<<<<<<< HEAD
=======

>>>>>>> a1abf2231ceadb16c3538774fc50b7415b1816d4
      /**
       * <code>.MessageType messageType = 1;</code>
       */
      public Builder clearMessageType() {

        messageType_ = 0;
        onChanged();
        return this;
      }

<<<<<<< HEAD
      private NettyData.Data data_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          NettyData.Data, NettyData.Data.Builder, NettyData.DataOrBuilder> dataBuilder_;
=======
>>>>>>> a1abf2231ceadb16c3538774fc50b7415b1816d4
      /**
       * <code>.Data data = 2;</code>
       */
      public boolean hasData() {
        return dataBuilder_ != null || data_ != null;
      }
<<<<<<< HEAD
=======

>>>>>>> a1abf2231ceadb16c3538774fc50b7415b1816d4
      /**
       * <code>.Data data = 2;</code>
       */
      public NettyData.Data getData() {
        if (dataBuilder_ == null) {
          return data_ == null ? NettyData.Data.getDefaultInstance() : data_;
        } else {
          return dataBuilder_.getMessage();
        }
      }
<<<<<<< HEAD
      /**
       * <code>.Data data = 2;</code>
       */
      public Builder setData(NettyData.Data value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          data_ = value;
          onChanged();
        } else {
          dataBuilder_.setMessage(value);
=======

      /**
       * <code>.Data data = 2;</code>
       */
      public Builder setData(
          NettyData.Data.Builder builderForValue) {
        if (dataBuilder_ == null) {
          data_ = builderForValue.build();
          onChanged();
        } else {
          dataBuilder_.setMessage(builderForValue.build());
>>>>>>> a1abf2231ceadb16c3538774fc50b7415b1816d4
        }

        return this;
      }
<<<<<<< HEAD
      /**
       * <code>.Data data = 2;</code>
       */
      public Builder setData(
          NettyData.Data.Builder builderForValue) {
        if (dataBuilder_ == null) {
          data_ = builderForValue.build();
          onChanged();
        } else {
          dataBuilder_.setMessage(builderForValue.build());
=======

      /**
       * <code>.Data data = 2;</code>
       */
      public Builder setData(NettyData.Data value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          data_ = value;
          onChanged();
        } else {
          dataBuilder_.setMessage(value);
>>>>>>> a1abf2231ceadb16c3538774fc50b7415b1816d4
        }

        return this;
      }
<<<<<<< HEAD
=======

>>>>>>> a1abf2231ceadb16c3538774fc50b7415b1816d4
      /**
       * <code>.Data data = 2;</code>
       */
      public Builder mergeData(NettyData.Data value) {
        if (dataBuilder_ == null) {
          if (data_ != null) {
            data_ =
<<<<<<< HEAD
              NettyData.Data.newBuilder(data_).mergeFrom(value).buildPartial();
=======
                NettyData.Data.newBuilder(data_).mergeFrom(value).buildPartial();
>>>>>>> a1abf2231ceadb16c3538774fc50b7415b1816d4
          } else {
            data_ = value;
          }
          onChanged();
        } else {
          dataBuilder_.mergeFrom(value);
        }

        return this;
      }
<<<<<<< HEAD
=======

>>>>>>> a1abf2231ceadb16c3538774fc50b7415b1816d4
      /**
       * <code>.Data data = 2;</code>
       */
      public Builder clearData() {
        if (dataBuilder_ == null) {
          data_ = null;
          onChanged();
        } else {
          data_ = null;
          dataBuilder_ = null;
        }

        return this;
      }
<<<<<<< HEAD
=======

>>>>>>> a1abf2231ceadb16c3538774fc50b7415b1816d4
      /**
       * <code>.Data data = 2;</code>
       */
      public NettyData.Data.Builder getDataBuilder() {

        onChanged();
        return getDataFieldBuilder().getBuilder();
      }
<<<<<<< HEAD
=======

>>>>>>> a1abf2231ceadb16c3538774fc50b7415b1816d4
      /**
       * <code>.Data data = 2;</code>
       */
      public NettyData.DataOrBuilder getDataOrBuilder() {
        if (dataBuilder_ != null) {
          return dataBuilder_.getMessageOrBuilder();
        } else {
          return data_ == null ?
              NettyData.Data.getDefaultInstance() : data_;
        }
      }
<<<<<<< HEAD
=======

>>>>>>> a1abf2231ceadb16c3538774fc50b7415b1816d4
      /**
       * <code>.Data data = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          NettyData.Data, NettyData.Data.Builder, NettyData.DataOrBuilder>
<<<<<<< HEAD
          getDataFieldBuilder() {
        if (dataBuilder_ == null) {
          dataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              NettyData.Data, NettyData.Data.Builder, NettyData.DataOrBuilder>(
                  getData(),
                  getParentForChildren(),
                  isClean());
=======
      getDataFieldBuilder() {
        if (dataBuilder_ == null) {
          dataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              NettyData.Data, NettyData.Data.Builder, NettyData.DataOrBuilder>(
              getData(),
              getParentForChildren(),
              isClean());
>>>>>>> a1abf2231ceadb16c3538774fc50b7415b1816d4
          data_ = null;
        }
        return dataBuilder_;
      }
<<<<<<< HEAD
=======

>>>>>>> a1abf2231ceadb16c3538774fc50b7415b1816d4
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

<<<<<<< HEAD

      // @@protoc_insertion_point(builder_scope:Message)
    }

    // @@protoc_insertion_point(class_scope:Message)
    private static final NettyMessage.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new NettyMessage.Message();
    }

    public static NettyMessage.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    public NettyMessage.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022NettyMessage.proto\032\021MessageType.proto\032" +
      "\017NettyData.proto\"A\n\007Message\022!\n\013messageTy" +
      "pe\030\001 \001(\0162\014.MessageType\022\023\n\004data\030\002 \001(\0132\005.D" +
      "ataB\"\n\022com.passport.protoB\014NettyMessageb" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          MessageTypeEnum.getDescriptor(),
          NettyData.getDescriptor(),
        }, assigner);
    internal_static_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_descriptor,
        new String[] { "MessageType", "Data", });
    MessageTypeEnum.getDescriptor();
    NettyData.getDescriptor();
=======
      // @@protoc_insertion_point(builder_scope:Message)
    }

>>>>>>> a1abf2231ceadb16c3538774fc50b7415b1816d4
  }

  // @@protoc_insertion_point(outer_class_scope)
}
