// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NettyData.proto

package com.passport.proto;

public final class NettyData {
  private NettyData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Data)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.DataType dataType = 1;</code>
     */
    int getDataTypeValue();
    /**
     * <code>.DataType dataType = 1;</code>
     */
    DataTypeEnum.DataType getDataType();

    /**
     * <code>.Block block = 2;</code>
     */
    boolean hasBlock();
    /**
     * <code>.Block block = 2;</code>
     */
    BlockMessage.Block getBlock();
    /**
     * <code>.Block block = 2;</code>
     */
    BlockMessage.BlockOrBuilder getBlockOrBuilder();

    /**
     * <code>repeated .Account accounts = 3;</code>
     */
    java.util.List<AccountMessage.Account>
        getAccountsList();
    /**
     * <code>repeated .Account accounts = 3;</code>
     */
    AccountMessage.Account getAccounts(int index);
    /**
     * <code>repeated .Account accounts = 3;</code>
     */
    int getAccountsCount();
    /**
     * <code>repeated .Account accounts = 3;</code>
     */
    java.util.List<? extends AccountMessage.AccountOrBuilder>
        getAccountsOrBuilderList();
    /**
     * <code>repeated .Account accounts = 3;</code>
     */
    AccountMessage.AccountOrBuilder getAccountsOrBuilder(
            int index);

    /**
     * <code>repeated .Block blocks = 4;</code>
     */
    java.util.List<BlockMessage.Block>
        getBlocksList();
    /**
     * <code>repeated .Block blocks = 4;</code>
     */
    BlockMessage.Block getBlocks(int index);
    /**
     * <code>repeated .Block blocks = 4;</code>
     */
    int getBlocksCount();
    /**
     * <code>repeated .Block blocks = 4;</code>
     */
    java.util.List<? extends BlockMessage.BlockOrBuilder>
        getBlocksOrBuilderList();
    /**
     * <code>repeated .Block blocks = 4;</code>
     */
    BlockMessage.BlockOrBuilder getBlocksOrBuilder(
            int index);

    /**
     * <code>.Account account = 5;</code>
     */
    boolean hasAccount();
    /**
     * <code>.Account account = 5;</code>
     */
    AccountMessage.Account getAccount();
    /**
     * <code>.Account account = 5;</code>
     */
    AccountMessage.AccountOrBuilder getAccountOrBuilder();

    /**
     * <code>.Transaction transaction = 6;</code>
     */
    boolean hasTransaction();
    /**
     * <code>.Transaction transaction = 6;</code>
     */
    TransactionMessage.Transaction getTransaction();
    /**
     * <code>.Transaction transaction = 6;</code>
     */
    TransactionMessage.TransactionOrBuilder getTransactionOrBuilder();
  }
  /**
   * Protobuf type {@code Data}
   */
  public  static final class Data extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Data)
      DataOrBuilder {
    // Use Data.newBuilder() to construct.
    private Data(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Data() {
      dataType_ = 0;
      accounts_ = java.util.Collections.emptyList();
      blocks_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Data(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              dataType_ = rawValue;
              break;
            }
            case 18: {
              BlockMessage.Block.Builder subBuilder = null;
              if (block_ != null) {
                subBuilder = block_.toBuilder();
              }
              block_ = input.readMessage(BlockMessage.Block.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(block_);
                block_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                accounts_ = new java.util.ArrayList<AccountMessage.Account>();
                mutable_bitField0_ |= 0x00000004;
              }
              accounts_.add(
                  input.readMessage(AccountMessage.Account.parser(), extensionRegistry));
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                blocks_ = new java.util.ArrayList<BlockMessage.Block>();
                mutable_bitField0_ |= 0x00000008;
              }
              blocks_.add(
                  input.readMessage(BlockMessage.Block.parser(), extensionRegistry));
              break;
            }
            case 42: {
              AccountMessage.Account.Builder subBuilder = null;
              if (account_ != null) {
                subBuilder = account_.toBuilder();
              }
              account_ = input.readMessage(AccountMessage.Account.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(account_);
                account_ = subBuilder.buildPartial();
              }

              break;
            }
            case 50: {
              TransactionMessage.Transaction.Builder subBuilder = null;
              if (transaction_ != null) {
                subBuilder = transaction_.toBuilder();
              }
              transaction_ = input.readMessage(TransactionMessage.Transaction.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(transaction_);
                transaction_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          accounts_ = java.util.Collections.unmodifiableList(accounts_);
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          blocks_ = java.util.Collections.unmodifiableList(blocks_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return NettyData.internal_static_Data_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return NettyData.internal_static_Data_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              NettyData.Data.class, NettyData.Data.Builder.class);
    }

    private int bitField0_;
    public static final int DATATYPE_FIELD_NUMBER = 1;
    private int dataType_;
    /**
     * <code>.DataType dataType = 1;</code>
     */
    public int getDataTypeValue() {
      return dataType_;
    }
    /**
     * <code>.DataType dataType = 1;</code>
     */
    public DataTypeEnum.DataType getDataType() {
      DataTypeEnum.DataType result = DataTypeEnum.DataType.valueOf(dataType_);
      return result == null ? DataTypeEnum.DataType.UNRECOGNIZED : result;
    }

    public static final int BLOCK_FIELD_NUMBER = 2;
    private BlockMessage.Block block_;
    /**
     * <code>.Block block = 2;</code>
     */
    public boolean hasBlock() {
      return block_ != null;
    }
    /**
     * <code>.Block block = 2;</code>
     */
    public BlockMessage.Block getBlock() {
      return block_ == null ? BlockMessage.Block.getDefaultInstance() : block_;
    }
    /**
     * <code>.Block block = 2;</code>
     */
    public BlockMessage.BlockOrBuilder getBlockOrBuilder() {
      return getBlock();
    }

    public static final int ACCOUNTS_FIELD_NUMBER = 3;
    private java.util.List<AccountMessage.Account> accounts_;
    /**
     * <code>repeated .Account accounts = 3;</code>
     */
    public java.util.List<AccountMessage.Account> getAccountsList() {
      return accounts_;
    }
    /**
     * <code>repeated .Account accounts = 3;</code>
     */
    public java.util.List<? extends AccountMessage.AccountOrBuilder>
        getAccountsOrBuilderList() {
      return accounts_;
    }
    /**
     * <code>repeated .Account accounts = 3;</code>
     */
    public int getAccountsCount() {
      return accounts_.size();
    }
    /**
     * <code>repeated .Account accounts = 3;</code>
     */
    public AccountMessage.Account getAccounts(int index) {
      return accounts_.get(index);
    }
    /**
     * <code>repeated .Account accounts = 3;</code>
     */
    public AccountMessage.AccountOrBuilder getAccountsOrBuilder(
        int index) {
      return accounts_.get(index);
    }

    public static final int BLOCKS_FIELD_NUMBER = 4;
    private java.util.List<BlockMessage.Block> blocks_;
    /**
     * <code>repeated .Block blocks = 4;</code>
     */
    public java.util.List<BlockMessage.Block> getBlocksList() {
      return blocks_;
    }
    /**
     * <code>repeated .Block blocks = 4;</code>
     */
    public java.util.List<? extends BlockMessage.BlockOrBuilder>
        getBlocksOrBuilderList() {
      return blocks_;
    }
    /**
     * <code>repeated .Block blocks = 4;</code>
     */
    public int getBlocksCount() {
      return blocks_.size();
    }
    /**
     * <code>repeated .Block blocks = 4;</code>
     */
    public BlockMessage.Block getBlocks(int index) {
      return blocks_.get(index);
    }
    /**
     * <code>repeated .Block blocks = 4;</code>
     */
    public BlockMessage.BlockOrBuilder getBlocksOrBuilder(
        int index) {
      return blocks_.get(index);
    }

    public static final int ACCOUNT_FIELD_NUMBER = 5;
    private AccountMessage.Account account_;
    /**
     * <code>.Account account = 5;</code>
     */
    public boolean hasAccount() {
      return account_ != null;
    }
    /**
     * <code>.Account account = 5;</code>
     */
    public AccountMessage.Account getAccount() {
      return account_ == null ? AccountMessage.Account.getDefaultInstance() : account_;
    }
    /**
     * <code>.Account account = 5;</code>
     */
    public AccountMessage.AccountOrBuilder getAccountOrBuilder() {
      return getAccount();
    }

    public static final int TRANSACTION_FIELD_NUMBER = 6;
    private TransactionMessage.Transaction transaction_;
    /**
     * <code>.Transaction transaction = 6;</code>
     */
    public boolean hasTransaction() {
      return transaction_ != null;
    }
    /**
     * <code>.Transaction transaction = 6;</code>
     */
    public TransactionMessage.Transaction getTransaction() {
      return transaction_ == null ? TransactionMessage.Transaction.getDefaultInstance() : transaction_;
    }
    /**
     * <code>.Transaction transaction = 6;</code>
     */
    public TransactionMessage.TransactionOrBuilder getTransactionOrBuilder() {
      return getTransaction();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (dataType_ != DataTypeEnum.DataType.HEART_BEAT.getNumber()) {
        output.writeEnum(1, dataType_);
      }
      if (block_ != null) {
        output.writeMessage(2, getBlock());
      }
      for (int i = 0; i < accounts_.size(); i++) {
        output.writeMessage(3, accounts_.get(i));
      }
      for (int i = 0; i < blocks_.size(); i++) {
        output.writeMessage(4, blocks_.get(i));
      }
      if (account_ != null) {
        output.writeMessage(5, getAccount());
      }
      if (transaction_ != null) {
        output.writeMessage(6, getTransaction());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (dataType_ != DataTypeEnum.DataType.HEART_BEAT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, dataType_);
      }
      if (block_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getBlock());
      }
      for (int i = 0; i < accounts_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, accounts_.get(i));
      }
      for (int i = 0; i < blocks_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, blocks_.get(i));
      }
      if (account_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getAccount());
      }
      if (transaction_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getTransaction());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof NettyData.Data)) {
        return super.equals(obj);
      }
      NettyData.Data other = (NettyData.Data) obj;

      boolean result = true;
      result = result && dataType_ == other.dataType_;
      result = result && (hasBlock() == other.hasBlock());
      if (hasBlock()) {
        result = result && getBlock()
            .equals(other.getBlock());
      }
      result = result && getAccountsList()
          .equals(other.getAccountsList());
      result = result && getBlocksList()
          .equals(other.getBlocksList());
      result = result && (hasAccount() == other.hasAccount());
      if (hasAccount()) {
        result = result && getAccount()
            .equals(other.getAccount());
      }
      result = result && (hasTransaction() == other.hasTransaction());
      if (hasTransaction()) {
        result = result && getTransaction()
            .equals(other.getTransaction());
      }
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DATATYPE_FIELD_NUMBER;
      hash = (53 * hash) + dataType_;
      if (hasBlock()) {
        hash = (37 * hash) + BLOCK_FIELD_NUMBER;
        hash = (53 * hash) + getBlock().hashCode();
      }
      if (getAccountsCount() > 0) {
        hash = (37 * hash) + ACCOUNTS_FIELD_NUMBER;
        hash = (53 * hash) + getAccountsList().hashCode();
      }
      if (getBlocksCount() > 0) {
        hash = (37 * hash) + BLOCKS_FIELD_NUMBER;
        hash = (53 * hash) + getBlocksList().hashCode();
      }
      if (hasAccount()) {
        hash = (37 * hash) + ACCOUNT_FIELD_NUMBER;
        hash = (53 * hash) + getAccount().hashCode();
      }
      if (hasTransaction()) {
        hash = (37 * hash) + TRANSACTION_FIELD_NUMBER;
        hash = (53 * hash) + getTransaction().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static NettyData.Data parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NettyData.Data parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NettyData.Data parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NettyData.Data parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NettyData.Data parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NettyData.Data parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NettyData.Data parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static NettyData.Data parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static NettyData.Data parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static NettyData.Data parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static NettyData.Data parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static NettyData.Data parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(NettyData.Data prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Data}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Data)
        NettyData.DataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return NettyData.internal_static_Data_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return NettyData.internal_static_Data_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                NettyData.Data.class, NettyData.Data.Builder.class);
      }

      // Construct using com.passport.proto.NettyData.Data.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAccountsFieldBuilder();
          getBlocksFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        dataType_ = 0;

        if (blockBuilder_ == null) {
          block_ = null;
        } else {
          block_ = null;
          blockBuilder_ = null;
        }
        if (accountsBuilder_ == null) {
          accounts_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          accountsBuilder_.clear();
        }
        if (blocksBuilder_ == null) {
          blocks_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          blocksBuilder_.clear();
        }
        if (accountBuilder_ == null) {
          account_ = null;
        } else {
          account_ = null;
          accountBuilder_ = null;
        }
        if (transactionBuilder_ == null) {
          transaction_ = null;
        } else {
          transaction_ = null;
          transactionBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return NettyData.internal_static_Data_descriptor;
      }

      public NettyData.Data getDefaultInstanceForType() {
        return NettyData.Data.getDefaultInstance();
      }

      public NettyData.Data build() {
        NettyData.Data result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public NettyData.Data buildPartial() {
        NettyData.Data result = new NettyData.Data(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.dataType_ = dataType_;
        if (blockBuilder_ == null) {
          result.block_ = block_;
        } else {
          result.block_ = blockBuilder_.build();
        }
        if (accountsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            accounts_ = java.util.Collections.unmodifiableList(accounts_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.accounts_ = accounts_;
        } else {
          result.accounts_ = accountsBuilder_.build();
        }
        if (blocksBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            blocks_ = java.util.Collections.unmodifiableList(blocks_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.blocks_ = blocks_;
        } else {
          result.blocks_ = blocksBuilder_.build();
        }
        if (accountBuilder_ == null) {
          result.account_ = account_;
        } else {
          result.account_ = accountBuilder_.build();
        }
        if (transactionBuilder_ == null) {
          result.transaction_ = transaction_;
        } else {
          result.transaction_ = transactionBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof NettyData.Data) {
          return mergeFrom((NettyData.Data)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(NettyData.Data other) {
        if (other == NettyData.Data.getDefaultInstance()) return this;
        if (other.dataType_ != 0) {
          setDataTypeValue(other.getDataTypeValue());
        }
        if (other.hasBlock()) {
          mergeBlock(other.getBlock());
        }
        if (accountsBuilder_ == null) {
          if (!other.accounts_.isEmpty()) {
            if (accounts_.isEmpty()) {
              accounts_ = other.accounts_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureAccountsIsMutable();
              accounts_.addAll(other.accounts_);
            }
            onChanged();
          }
        } else {
          if (!other.accounts_.isEmpty()) {
            if (accountsBuilder_.isEmpty()) {
              accountsBuilder_.dispose();
              accountsBuilder_ = null;
              accounts_ = other.accounts_;
              bitField0_ = (bitField0_ & ~0x00000004);
              accountsBuilder_ =
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAccountsFieldBuilder() : null;
            } else {
              accountsBuilder_.addAllMessages(other.accounts_);
            }
          }
        }
        if (blocksBuilder_ == null) {
          if (!other.blocks_.isEmpty()) {
            if (blocks_.isEmpty()) {
              blocks_ = other.blocks_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureBlocksIsMutable();
              blocks_.addAll(other.blocks_);
            }
            onChanged();
          }
        } else {
          if (!other.blocks_.isEmpty()) {
            if (blocksBuilder_.isEmpty()) {
              blocksBuilder_.dispose();
              blocksBuilder_ = null;
              blocks_ = other.blocks_;
              bitField0_ = (bitField0_ & ~0x00000008);
              blocksBuilder_ =
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getBlocksFieldBuilder() : null;
            } else {
              blocksBuilder_.addAllMessages(other.blocks_);
            }
          }
        }
        if (other.hasAccount()) {
          mergeAccount(other.getAccount());
        }
        if (other.hasTransaction()) {
          mergeTransaction(other.getTransaction());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        NettyData.Data parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (NettyData.Data) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int dataType_ = 0;
      /**
       * <code>.DataType dataType = 1;</code>
       */
      public int getDataTypeValue() {
        return dataType_;
      }
      /**
       * <code>.DataType dataType = 1;</code>
       */
      public Builder setDataTypeValue(int value) {
        dataType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.DataType dataType = 1;</code>
       */
      public DataTypeEnum.DataType getDataType() {
        DataTypeEnum.DataType result = DataTypeEnum.DataType.valueOf(dataType_);
        return result == null ? DataTypeEnum.DataType.UNRECOGNIZED : result;
      }
      /**
       * <code>.DataType dataType = 1;</code>
       */
      public Builder setDataType(DataTypeEnum.DataType value) {
        if (value == null) {
          throw new NullPointerException();
        }

        dataType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.DataType dataType = 1;</code>
       */
      public Builder clearDataType() {

        dataType_ = 0;
        onChanged();
        return this;
      }

      private BlockMessage.Block block_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          BlockMessage.Block, BlockMessage.Block.Builder, BlockMessage.BlockOrBuilder> blockBuilder_;
      /**
       * <code>.Block block = 2;</code>
       */
      public boolean hasBlock() {
        return blockBuilder_ != null || block_ != null;
      }
      /**
       * <code>.Block block = 2;</code>
       */
      public BlockMessage.Block getBlock() {
        if (blockBuilder_ == null) {
          return block_ == null ? BlockMessage.Block.getDefaultInstance() : block_;
        } else {
          return blockBuilder_.getMessage();
        }
      }
      /**
       * <code>.Block block = 2;</code>
       */
      public Builder setBlock(BlockMessage.Block value) {
        if (blockBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          block_ = value;
          onChanged();
        } else {
          blockBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Block block = 2;</code>
       */
      public Builder setBlock(
          BlockMessage.Block.Builder builderForValue) {
        if (blockBuilder_ == null) {
          block_ = builderForValue.build();
          onChanged();
        } else {
          blockBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Block block = 2;</code>
       */
      public Builder mergeBlock(BlockMessage.Block value) {
        if (blockBuilder_ == null) {
          if (block_ != null) {
            block_ =
              BlockMessage.Block.newBuilder(block_).mergeFrom(value).buildPartial();
          } else {
            block_ = value;
          }
          onChanged();
        } else {
          blockBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Block block = 2;</code>
       */
      public Builder clearBlock() {
        if (blockBuilder_ == null) {
          block_ = null;
          onChanged();
        } else {
          block_ = null;
          blockBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Block block = 2;</code>
       */
      public BlockMessage.Block.Builder getBlockBuilder() {

        onChanged();
        return getBlockFieldBuilder().getBuilder();
      }
      /**
       * <code>.Block block = 2;</code>
       */
      public BlockMessage.BlockOrBuilder getBlockOrBuilder() {
        if (blockBuilder_ != null) {
          return blockBuilder_.getMessageOrBuilder();
        } else {
          return block_ == null ?
              BlockMessage.Block.getDefaultInstance() : block_;
        }
      }
      /**
       * <code>.Block block = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          BlockMessage.Block, BlockMessage.Block.Builder, BlockMessage.BlockOrBuilder>
          getBlockFieldBuilder() {
        if (blockBuilder_ == null) {
          blockBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              BlockMessage.Block, BlockMessage.Block.Builder, BlockMessage.BlockOrBuilder>(
                  getBlock(),
                  getParentForChildren(),
                  isClean());
          block_ = null;
        }
        return blockBuilder_;
      }

      private java.util.List<AccountMessage.Account> accounts_ =
        java.util.Collections.emptyList();
      private void ensureAccountsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          accounts_ = new java.util.ArrayList<AccountMessage.Account>(accounts_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          AccountMessage.Account, AccountMessage.Account.Builder, AccountMessage.AccountOrBuilder> accountsBuilder_;

      /**
       * <code>repeated .Account accounts = 3;</code>
       */
      public java.util.List<AccountMessage.Account> getAccountsList() {
        if (accountsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(accounts_);
        } else {
          return accountsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Account accounts = 3;</code>
       */
      public int getAccountsCount() {
        if (accountsBuilder_ == null) {
          return accounts_.size();
        } else {
          return accountsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Account accounts = 3;</code>
       */
      public AccountMessage.Account getAccounts(int index) {
        if (accountsBuilder_ == null) {
          return accounts_.get(index);
        } else {
          return accountsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Account accounts = 3;</code>
       */
      public Builder setAccounts(
          int index, AccountMessage.Account value) {
        if (accountsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAccountsIsMutable();
          accounts_.set(index, value);
          onChanged();
        } else {
          accountsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Account accounts = 3;</code>
       */
      public Builder setAccounts(
          int index, AccountMessage.Account.Builder builderForValue) {
        if (accountsBuilder_ == null) {
          ensureAccountsIsMutable();
          accounts_.set(index, builderForValue.build());
          onChanged();
        } else {
          accountsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Account accounts = 3;</code>
       */
      public Builder addAccounts(AccountMessage.Account value) {
        if (accountsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAccountsIsMutable();
          accounts_.add(value);
          onChanged();
        } else {
          accountsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Account accounts = 3;</code>
       */
      public Builder addAccounts(
          int index, AccountMessage.Account value) {
        if (accountsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAccountsIsMutable();
          accounts_.add(index, value);
          onChanged();
        } else {
          accountsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Account accounts = 3;</code>
       */
      public Builder addAccounts(
          AccountMessage.Account.Builder builderForValue) {
        if (accountsBuilder_ == null) {
          ensureAccountsIsMutable();
          accounts_.add(builderForValue.build());
          onChanged();
        } else {
          accountsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Account accounts = 3;</code>
       */
      public Builder addAccounts(
          int index, AccountMessage.Account.Builder builderForValue) {
        if (accountsBuilder_ == null) {
          ensureAccountsIsMutable();
          accounts_.add(index, builderForValue.build());
          onChanged();
        } else {
          accountsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Account accounts = 3;</code>
       */
      public Builder addAllAccounts(
          Iterable<? extends AccountMessage.Account> values) {
        if (accountsBuilder_ == null) {
          ensureAccountsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, accounts_);
          onChanged();
        } else {
          accountsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Account accounts = 3;</code>
       */
      public Builder clearAccounts() {
        if (accountsBuilder_ == null) {
          accounts_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          accountsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Account accounts = 3;</code>
       */
      public Builder removeAccounts(int index) {
        if (accountsBuilder_ == null) {
          ensureAccountsIsMutable();
          accounts_.remove(index);
          onChanged();
        } else {
          accountsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Account accounts = 3;</code>
       */
      public AccountMessage.Account.Builder getAccountsBuilder(
          int index) {
        return getAccountsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Account accounts = 3;</code>
       */
      public AccountMessage.AccountOrBuilder getAccountsOrBuilder(
          int index) {
        if (accountsBuilder_ == null) {
          return accounts_.get(index);  } else {
          return accountsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Account accounts = 3;</code>
       */
      public java.util.List<? extends AccountMessage.AccountOrBuilder>
           getAccountsOrBuilderList() {
        if (accountsBuilder_ != null) {
          return accountsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(accounts_);
        }
      }
      /**
       * <code>repeated .Account accounts = 3;</code>
       */
      public AccountMessage.Account.Builder addAccountsBuilder() {
        return getAccountsFieldBuilder().addBuilder(
            AccountMessage.Account.getDefaultInstance());
      }
      /**
       * <code>repeated .Account accounts = 3;</code>
       */
      public AccountMessage.Account.Builder addAccountsBuilder(
          int index) {
        return getAccountsFieldBuilder().addBuilder(
            index, AccountMessage.Account.getDefaultInstance());
      }
      /**
       * <code>repeated .Account accounts = 3;</code>
       */
      public java.util.List<AccountMessage.Account.Builder>
           getAccountsBuilderList() {
        return getAccountsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          AccountMessage.Account, AccountMessage.Account.Builder, AccountMessage.AccountOrBuilder>
          getAccountsFieldBuilder() {
        if (accountsBuilder_ == null) {
          accountsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              AccountMessage.Account, AccountMessage.Account.Builder, AccountMessage.AccountOrBuilder>(
                  accounts_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          accounts_ = null;
        }
        return accountsBuilder_;
      }

      private java.util.List<BlockMessage.Block> blocks_ =
        java.util.Collections.emptyList();
      private void ensureBlocksIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          blocks_ = new java.util.ArrayList<BlockMessage.Block>(blocks_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          BlockMessage.Block, BlockMessage.Block.Builder, BlockMessage.BlockOrBuilder> blocksBuilder_;

      /**
       * <code>repeated .Block blocks = 4;</code>
       */
      public java.util.List<BlockMessage.Block> getBlocksList() {
        if (blocksBuilder_ == null) {
          return java.util.Collections.unmodifiableList(blocks_);
        } else {
          return blocksBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Block blocks = 4;</code>
       */
      public int getBlocksCount() {
        if (blocksBuilder_ == null) {
          return blocks_.size();
        } else {
          return blocksBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Block blocks = 4;</code>
       */
      public BlockMessage.Block getBlocks(int index) {
        if (blocksBuilder_ == null) {
          return blocks_.get(index);
        } else {
          return blocksBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Block blocks = 4;</code>
       */
      public Builder setBlocks(
          int index, BlockMessage.Block value) {
        if (blocksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBlocksIsMutable();
          blocks_.set(index, value);
          onChanged();
        } else {
          blocksBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Block blocks = 4;</code>
       */
      public Builder setBlocks(
          int index, BlockMessage.Block.Builder builderForValue) {
        if (blocksBuilder_ == null) {
          ensureBlocksIsMutable();
          blocks_.set(index, builderForValue.build());
          onChanged();
        } else {
          blocksBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Block blocks = 4;</code>
       */
      public Builder addBlocks(BlockMessage.Block value) {
        if (blocksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBlocksIsMutable();
          blocks_.add(value);
          onChanged();
        } else {
          blocksBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Block blocks = 4;</code>
       */
      public Builder addBlocks(
          int index, BlockMessage.Block value) {
        if (blocksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBlocksIsMutable();
          blocks_.add(index, value);
          onChanged();
        } else {
          blocksBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Block blocks = 4;</code>
       */
      public Builder addBlocks(
          BlockMessage.Block.Builder builderForValue) {
        if (blocksBuilder_ == null) {
          ensureBlocksIsMutable();
          blocks_.add(builderForValue.build());
          onChanged();
        } else {
          blocksBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Block blocks = 4;</code>
       */
      public Builder addBlocks(
          int index, BlockMessage.Block.Builder builderForValue) {
        if (blocksBuilder_ == null) {
          ensureBlocksIsMutable();
          blocks_.add(index, builderForValue.build());
          onChanged();
        } else {
          blocksBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Block blocks = 4;</code>
       */
      public Builder addAllBlocks(
          Iterable<? extends BlockMessage.Block> values) {
        if (blocksBuilder_ == null) {
          ensureBlocksIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, blocks_);
          onChanged();
        } else {
          blocksBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Block blocks = 4;</code>
       */
      public Builder clearBlocks() {
        if (blocksBuilder_ == null) {
          blocks_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          blocksBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Block blocks = 4;</code>
       */
      public Builder removeBlocks(int index) {
        if (blocksBuilder_ == null) {
          ensureBlocksIsMutable();
          blocks_.remove(index);
          onChanged();
        } else {
          blocksBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Block blocks = 4;</code>
       */
      public BlockMessage.Block.Builder getBlocksBuilder(
          int index) {
        return getBlocksFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Block blocks = 4;</code>
       */
      public BlockMessage.BlockOrBuilder getBlocksOrBuilder(
          int index) {
        if (blocksBuilder_ == null) {
          return blocks_.get(index);  } else {
          return blocksBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Block blocks = 4;</code>
       */
      public java.util.List<? extends BlockMessage.BlockOrBuilder>
           getBlocksOrBuilderList() {
        if (blocksBuilder_ != null) {
          return blocksBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(blocks_);
        }
      }
      /**
       * <code>repeated .Block blocks = 4;</code>
       */
      public BlockMessage.Block.Builder addBlocksBuilder() {
        return getBlocksFieldBuilder().addBuilder(
            BlockMessage.Block.getDefaultInstance());
      }
      /**
       * <code>repeated .Block blocks = 4;</code>
       */
      public BlockMessage.Block.Builder addBlocksBuilder(
          int index) {
        return getBlocksFieldBuilder().addBuilder(
            index, BlockMessage.Block.getDefaultInstance());
      }
      /**
       * <code>repeated .Block blocks = 4;</code>
       */
      public java.util.List<BlockMessage.Block.Builder>
           getBlocksBuilderList() {
        return getBlocksFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          BlockMessage.Block, BlockMessage.Block.Builder, BlockMessage.BlockOrBuilder>
          getBlocksFieldBuilder() {
        if (blocksBuilder_ == null) {
          blocksBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              BlockMessage.Block, BlockMessage.Block.Builder, BlockMessage.BlockOrBuilder>(
                  blocks_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          blocks_ = null;
        }
        return blocksBuilder_;
      }

      private AccountMessage.Account account_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          AccountMessage.Account, AccountMessage.Account.Builder, AccountMessage.AccountOrBuilder> accountBuilder_;
      /**
       * <code>.Account account = 5;</code>
       */
      public boolean hasAccount() {
        return accountBuilder_ != null || account_ != null;
      }
      /**
       * <code>.Account account = 5;</code>
       */
      public AccountMessage.Account getAccount() {
        if (accountBuilder_ == null) {
          return account_ == null ? AccountMessage.Account.getDefaultInstance() : account_;
        } else {
          return accountBuilder_.getMessage();
        }
      }
      /**
       * <code>.Account account = 5;</code>
       */
      public Builder setAccount(AccountMessage.Account value) {
        if (accountBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          account_ = value;
          onChanged();
        } else {
          accountBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Account account = 5;</code>
       */
      public Builder setAccount(
          AccountMessage.Account.Builder builderForValue) {
        if (accountBuilder_ == null) {
          account_ = builderForValue.build();
          onChanged();
        } else {
          accountBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Account account = 5;</code>
       */
      public Builder mergeAccount(AccountMessage.Account value) {
        if (accountBuilder_ == null) {
          if (account_ != null) {
            account_ =
              AccountMessage.Account.newBuilder(account_).mergeFrom(value).buildPartial();
          } else {
            account_ = value;
          }
          onChanged();
        } else {
          accountBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Account account = 5;</code>
       */
      public Builder clearAccount() {
        if (accountBuilder_ == null) {
          account_ = null;
          onChanged();
        } else {
          account_ = null;
          accountBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Account account = 5;</code>
       */
      public AccountMessage.Account.Builder getAccountBuilder() {

        onChanged();
        return getAccountFieldBuilder().getBuilder();
      }
      /**
       * <code>.Account account = 5;</code>
       */
      public AccountMessage.AccountOrBuilder getAccountOrBuilder() {
        if (accountBuilder_ != null) {
          return accountBuilder_.getMessageOrBuilder();
        } else {
          return account_ == null ?
              AccountMessage.Account.getDefaultInstance() : account_;
        }
      }
      /**
       * <code>.Account account = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          AccountMessage.Account, AccountMessage.Account.Builder, AccountMessage.AccountOrBuilder>
          getAccountFieldBuilder() {
        if (accountBuilder_ == null) {
          accountBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              AccountMessage.Account, AccountMessage.Account.Builder, AccountMessage.AccountOrBuilder>(
                  getAccount(),
                  getParentForChildren(),
                  isClean());
          account_ = null;
        }
        return accountBuilder_;
      }

      private TransactionMessage.Transaction transaction_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          TransactionMessage.Transaction, TransactionMessage.Transaction.Builder, TransactionMessage.TransactionOrBuilder> transactionBuilder_;
      /**
       * <code>.Transaction transaction = 6;</code>
       */
      public boolean hasTransaction() {
        return transactionBuilder_ != null || transaction_ != null;
      }
      /**
       * <code>.Transaction transaction = 6;</code>
       */
      public TransactionMessage.Transaction getTransaction() {
        if (transactionBuilder_ == null) {
          return transaction_ == null ? TransactionMessage.Transaction.getDefaultInstance() : transaction_;
        } else {
          return transactionBuilder_.getMessage();
        }
      }
      /**
       * <code>.Transaction transaction = 6;</code>
       */
      public Builder setTransaction(TransactionMessage.Transaction value) {
        if (transactionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          transaction_ = value;
          onChanged();
        } else {
          transactionBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Transaction transaction = 6;</code>
       */
      public Builder setTransaction(
          TransactionMessage.Transaction.Builder builderForValue) {
        if (transactionBuilder_ == null) {
          transaction_ = builderForValue.build();
          onChanged();
        } else {
          transactionBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Transaction transaction = 6;</code>
       */
      public Builder mergeTransaction(TransactionMessage.Transaction value) {
        if (transactionBuilder_ == null) {
          if (transaction_ != null) {
            transaction_ =
              TransactionMessage.Transaction.newBuilder(transaction_).mergeFrom(value).buildPartial();
          } else {
            transaction_ = value;
          }
          onChanged();
        } else {
          transactionBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Transaction transaction = 6;</code>
       */
      public Builder clearTransaction() {
        if (transactionBuilder_ == null) {
          transaction_ = null;
          onChanged();
        } else {
          transaction_ = null;
          transactionBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Transaction transaction = 6;</code>
       */
      public TransactionMessage.Transaction.Builder getTransactionBuilder() {

        onChanged();
        return getTransactionFieldBuilder().getBuilder();
      }
      /**
       * <code>.Transaction transaction = 6;</code>
       */
      public TransactionMessage.TransactionOrBuilder getTransactionOrBuilder() {
        if (transactionBuilder_ != null) {
          return transactionBuilder_.getMessageOrBuilder();
        } else {
          return transaction_ == null ?
              TransactionMessage.Transaction.getDefaultInstance() : transaction_;
        }
      }
      /**
       * <code>.Transaction transaction = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          TransactionMessage.Transaction, TransactionMessage.Transaction.Builder, TransactionMessage.TransactionOrBuilder>
          getTransactionFieldBuilder() {
        if (transactionBuilder_ == null) {
          transactionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              TransactionMessage.Transaction, TransactionMessage.Transaction.Builder, TransactionMessage.TransactionOrBuilder>(
                  getTransaction(),
                  getParentForChildren(),
                  isClean());
          transaction_ = null;
        }
        return transactionBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Data)
    }

    // @@protoc_insertion_point(class_scope:Data)
    private static final NettyData.Data DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new NettyData.Data();
    }

    public static NettyData.Data getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Data>
        PARSER = new com.google.protobuf.AbstractParser<Data>() {
      public Data parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Data(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Data> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Data> getParserForType() {
      return PARSER;
    }

    public NettyData.Data getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Data_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Data_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017NettyData.proto\032\016DataType.proto\032\022Block" +
      "Message.proto\032\024AccountMessage.proto\032\030Tra" +
      "nsactionMessage.proto\"\254\001\n\004Data\022\033\n\010dataTy" +
      "pe\030\001 \001(\0162\t.DataType\022\025\n\005block\030\002 \001(\0132\006.Blo" +
      "ck\022\032\n\010accounts\030\003 \003(\0132\010.Account\022\026\n\006blocks" +
      "\030\004 \003(\0132\006.Block\022\031\n\007account\030\005 \001(\0132\010.Accoun" +
      "t\022!\n\013transaction\030\006 \001(\0132\014.TransactionB\037\n\022" +
      "com.passport.protoB\tNettyDatab\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          DataTypeEnum.getDescriptor(),
          BlockMessage.getDescriptor(),
          AccountMessage.getDescriptor(),
          TransactionMessage.getDescriptor(),
        }, assigner);
    internal_static_Data_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Data_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Data_descriptor,
        new String[] { "DataType", "Block", "Accounts", "Blocks", "Account", "Transaction", });
    DataTypeEnum.getDescriptor();
    BlockMessage.getDescriptor();
    AccountMessage.getDescriptor();
    TransactionMessage.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
