// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TrusteeMessage.proto

package com.passport.proto;

public final class TrusteeMessage {
  private TrusteeMessage() {}
  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
            (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TrusteeOrBuilder extends
          // @@protoc_insertion_point(interface_extends:Trustee)
          com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes address = 1;</code>
     */
    com.google.protobuf.ByteString getAddress();

    /**
     * <code>int64 votes = 2;</code>
     */
    long getVotes();

    /**
     * <code>float generateRate = 3;</code>
     */
    float getGenerateRate();

    /**
     * <code>int64 status = 4;</code>
     */
    long getStatus();

    /**
     * <code>int64 state = 5;</code>
     */
    long getState();
  }
  /**
   * Protobuf type {@code Trustee}
   */
  public  static final class Trustee extends
          com.google.protobuf.GeneratedMessageV3 implements
          // @@protoc_insertion_point(message_implements:Trustee)
          TrusteeOrBuilder {
    // Use Trustee.newBuilder() to construct.
    private Trustee(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Trustee() {
      address_ = com.google.protobuf.ByteString.EMPTY;
      votes_ = 0L;
      generateRate_ = 0F;
      status_ = 0L;
      state_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Trustee(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              address_ = input.readBytes();
              break;
            }
            case 16: {

              votes_ = input.readInt64();
              break;
            }
            case 29: {

              generateRate_ = input.readFloat();
              break;
            }
            case 32: {

              status_ = input.readInt64();
              break;
            }
            case 40: {

              state_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
                e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return com.passport.proto.TrusteeMessage.internal_static_Trustee_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return com.passport.proto.TrusteeMessage.internal_static_Trustee_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      com.passport.proto.TrusteeMessage.Trustee.class, com.passport.proto.TrusteeMessage.Trustee.Builder.class);
    }

    public static final int ADDRESS_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString address_;
    /**
     * <code>bytes address = 1;</code>
     */
    public com.google.protobuf.ByteString getAddress() {
      return address_;
    }

    public static final int VOTES_FIELD_NUMBER = 2;
    private long votes_;
    /**
     * <code>int64 votes = 2;</code>
     */
    public long getVotes() {
      return votes_;
    }

    public static final int GENERATERATE_FIELD_NUMBER = 3;
    private float generateRate_;
    /**
     * <code>float generateRate = 3;</code>
     */
    public float getGenerateRate() {
      return generateRate_;
    }

    public static final int STATUS_FIELD_NUMBER = 4;
    private long status_;
    /**
     * <code>int64 status = 4;</code>
     */
    public long getStatus() {
      return status_;
    }

    public static final int STATE_FIELD_NUMBER = 5;
    private long state_;
    /**
     * <code>int64 state = 5;</code>
     */
    public long getState() {
      return state_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      if (!address_.isEmpty()) {
        output.writeBytes(1, address_);
      }
      if (votes_ != 0L) {
        output.writeInt64(2, votes_);
      }
      if (generateRate_ != 0F) {
        output.writeFloat(3, generateRate_);
      }
      if (status_ != 0L) {
        output.writeInt64(4, status_);
      }
      if (state_ != 0L) {
        output.writeInt64(5, state_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!address_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
                .computeBytesSize(1, address_);
      }
      if (votes_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt64Size(2, votes_);
      }
      if (generateRate_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
                .computeFloatSize(3, generateRate_);
      }
      if (status_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt64Size(4, status_);
      }
      if (state_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt64Size(5, state_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof com.passport.proto.TrusteeMessage.Trustee)) {
        return super.equals(obj);
      }
      com.passport.proto.TrusteeMessage.Trustee other = (com.passport.proto.TrusteeMessage.Trustee) obj;

      boolean result = true;
      result = result && getAddress()
              .equals(other.getAddress());
      result = result && (getVotes()
              == other.getVotes());
      result = result && (
              java.lang.Float.floatToIntBits(getGenerateRate())
                      == java.lang.Float.floatToIntBits(
                      other.getGenerateRate()));
      result = result && (getStatus()
              == other.getStatus());
      result = result && (getState()
              == other.getState());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
      hash = (37 * hash) + VOTES_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              getVotes());
      hash = (37 * hash) + GENERATERATE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
              getGenerateRate());
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              getStatus());
      hash = (37 * hash) + STATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              getState());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.passport.proto.TrusteeMessage.Trustee parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.passport.proto.TrusteeMessage.Trustee parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.passport.proto.TrusteeMessage.Trustee parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.passport.proto.TrusteeMessage.Trustee parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.passport.proto.TrusteeMessage.Trustee parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.passport.proto.TrusteeMessage.Trustee parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.passport.proto.TrusteeMessage.Trustee parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }
    public static com.passport.proto.TrusteeMessage.Trustee parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.passport.proto.TrusteeMessage.Trustee parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.passport.proto.TrusteeMessage.Trustee parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.passport.proto.TrusteeMessage.Trustee parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }
    public static com.passport.proto.TrusteeMessage.Trustee parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.passport.proto.TrusteeMessage.Trustee prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
              ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Trustee}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:Trustee)
            com.passport.proto.TrusteeMessage.TrusteeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return com.passport.proto.TrusteeMessage.internal_static_Trustee_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return com.passport.proto.TrusteeMessage.internal_static_Trustee_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        com.passport.proto.TrusteeMessage.Trustee.class, com.passport.proto.TrusteeMessage.Trustee.Builder.class);
      }

      // Construct using com.passport.proto.TrusteeMessage.Trustee.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
              com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        address_ = com.google.protobuf.ByteString.EMPTY;

        votes_ = 0L;

        generateRate_ = 0F;

        status_ = 0L;

        state_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return com.passport.proto.TrusteeMessage.internal_static_Trustee_descriptor;
      }

      public com.passport.proto.TrusteeMessage.Trustee getDefaultInstanceForType() {
        return com.passport.proto.TrusteeMessage.Trustee.getDefaultInstance();
      }

      public com.passport.proto.TrusteeMessage.Trustee build() {
        com.passport.proto.TrusteeMessage.Trustee result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.passport.proto.TrusteeMessage.Trustee buildPartial() {
        com.passport.proto.TrusteeMessage.Trustee result = new com.passport.proto.TrusteeMessage.Trustee(this);
        result.address_ = address_;
        result.votes_ = votes_;
        result.generateRate_ = generateRate_;
        result.status_ = status_;
        result.state_ = state_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
              com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
              com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.passport.proto.TrusteeMessage.Trustee) {
          return mergeFrom((com.passport.proto.TrusteeMessage.Trustee)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.passport.proto.TrusteeMessage.Trustee other) {
        if (other == com.passport.proto.TrusteeMessage.Trustee.getDefaultInstance()) return this;
        if (other.getAddress() != com.google.protobuf.ByteString.EMPTY) {
          setAddress(other.getAddress());
        }
        if (other.getVotes() != 0L) {
          setVotes(other.getVotes());
        }
        if (other.getGenerateRate() != 0F) {
          setGenerateRate(other.getGenerateRate());
        }
        if (other.getStatus() != 0L) {
          setStatus(other.getStatus());
        }
        if (other.getState() != 0L) {
          setState(other.getState());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        com.passport.proto.TrusteeMessage.Trustee parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.passport.proto.TrusteeMessage.Trustee) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString address_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes address = 1;</code>
       */
      public com.google.protobuf.ByteString getAddress() {
        return address_;
      }
      /**
       * <code>bytes address = 1;</code>
       */
      public Builder setAddress(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }

        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes address = 1;</code>
       */
      public Builder clearAddress() {

        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }

      private long votes_ ;
      /**
       * <code>int64 votes = 2;</code>
       */
      public long getVotes() {
        return votes_;
      }
      /**
       * <code>int64 votes = 2;</code>
       */
      public Builder setVotes(long value) {

        votes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 votes = 2;</code>
       */
      public Builder clearVotes() {

        votes_ = 0L;
        onChanged();
        return this;
      }

      private float generateRate_ ;
      /**
       * <code>float generateRate = 3;</code>
       */
      public float getGenerateRate() {
        return generateRate_;
      }
      /**
       * <code>float generateRate = 3;</code>
       */
      public Builder setGenerateRate(float value) {

        generateRate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float generateRate = 3;</code>
       */
      public Builder clearGenerateRate() {

        generateRate_ = 0F;
        onChanged();
        return this;
      }

      private long status_ ;
      /**
       * <code>int64 status = 4;</code>
       */
      public long getStatus() {
        return status_;
      }
      /**
       * <code>int64 status = 4;</code>
       */
      public Builder setStatus(long value) {

        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 status = 4;</code>
       */
      public Builder clearStatus() {

        status_ = 0L;
        onChanged();
        return this;
      }

      private long state_ ;
      /**
       * <code>int64 state = 5;</code>
       */
      public long getState() {
        return state_;
      }
      /**
       * <code>int64 state = 5;</code>
       */
      public Builder setState(long value) {

        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 state = 5;</code>
       */
      public Builder clearState() {

        state_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Trustee)
    }

    // @@protoc_insertion_point(class_scope:Trustee)
    private static final com.passport.proto.TrusteeMessage.Trustee DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.passport.proto.TrusteeMessage.Trustee();
    }

    public static com.passport.proto.TrusteeMessage.Trustee getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Trustee>
            PARSER = new com.google.protobuf.AbstractParser<Trustee>() {
      public Trustee parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return new Trustee(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Trustee> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Trustee> getParserForType() {
      return PARSER;
    }

    public com.passport.proto.TrusteeMessage.Trustee getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
          internal_static_Trustee_descriptor;
  private static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_Trustee_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
          descriptor;
  static {
    java.lang.String[] descriptorData = {
            "\n\024TrusteeMessage.proto\"^\n\007Trustee\022\017\n\007add" +
                    "ress\030\001 \001(\014\022\r\n\005votes\030\002 \001(\003\022\024\n\014generateRat" +
                    "e\030\003 \001(\002\022\016\n\006status\030\004 \001(\003\022\r\n\005state\030\005 \001(\003B$" +
                    "\n\022com.passport.protoB\016TrusteeMessageb\006pr" +
                    "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
            new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
              public com.google.protobuf.ExtensionRegistry assignDescriptors(
                      com.google.protobuf.Descriptors.FileDescriptor root) {
                descriptor = root;
                return null;
              }
            };
    com.google.protobuf.Descriptors.FileDescriptor
            .internalBuildGeneratedFileFrom(descriptorData,
                    new com.google.protobuf.Descriptors.FileDescriptor[] {
                    }, assigner);
    internal_static_Trustee_descriptor =
            getDescriptor().getMessageTypes().get(0);
    internal_static_Trustee_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_Trustee_descriptor,
            new java.lang.String[] { "Address", "Votes", "GenerateRate", "Status", "State", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
